#!/opt/local/bin/python

# 參考
# https://frostyx.cz/posts/vimwiki-diary-template

import sys
import datetime
import locale

locale.setlocale(locale.LC_TIME, "zh_TW")
locale.setlocale(locale.LC_TIME, "ja_JP")

template = """# {date}

## Daily checklist

* [ ] 記帳
* [ ] 料理

## Learning

## Notes"""

date = (datetime.date.today() if len(sys.argv) < 2
        # Expecting filename in YYYY-MM-DD.foo format
        else sys.argv[1].rsplit(".", 1)[0])
date = datetime.date.today()

print(template.format(date=date.strftime("%Y年%-m月%-d日%a曜日")))
